title: Wardat Shams Iqbal
name: Wardat Shams Iqbal
description: Computer science graduate working on machine learning, NLP, and research software.
url: "https://pineconedad.github.io"
baseurl: ""

markdown: kramdown
excerpt_separator: "\n\n"

collections:
  research:
    output: false
  other_projects:
    output: false
  experience:
    output: false
  miscellanea:
    output: false

sass:
  style: compressed

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - scripts
